/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Devuelve un JWT válido por 10 horas
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar opciones por tipo
         * @description Incluye activas e inactivas
         */
        get: operations["findByType"];
        put?: never;
        /** Crear una opción */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Editar o desactivar una opción
         * @description El tipo no se puede cambiar
         */
        put: operations["update_3"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar clientes
         * @description Ordenados por nombre
         */
        get: operations["findAll_1"];
        put?: never;
        /** Crear un cliente */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{clientId}/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar los equipos de un cliente */
        get: operations["findByClient"];
        put?: never;
        /** Crear un equipo para un cliente */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un cliente */
        get: operations["findById_2"];
        /** Editar un cliente */
        put: operations["update_2"];
        post?: never;
        /**
         * Eliminar un cliente
         * @description 409 si el cliente tiene equipos
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un equipo */
        get: operations["findById_1"];
        /** Editar un equipo */
        put: operations["update_1"];
        post?: never;
        /**
         * Eliminar un equipo
         * @description 409 si el equipo tiene informes
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technical-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar informes
         * @description Más recientes primero; filtros opcionales
         */
        get: operations["findAll"];
        put?: never;
        /**
         * Crear un informe
         * @description Asigna el número correlativo automáticamente
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technical-reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un informe */
        get: operations["findById"];
        /**
         * Editar un informe
         * @description No cambian el número ni el autor
         */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technical-reports/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar el informe en PDF */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CatalogCreateRequest: {
            /** @enum {string} */
            type: "ACTION" | "STATUS" | "EVENT_FAILURE" | "PERSONNEL" | "SUPERVISOR";
            value: string;
        };
        CatalogResponse: {
            active?: boolean;
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "ACTION" | "STATUS" | "EVENT_FAILURE" | "PERSONNEL" | "SUPERVISOR";
            value?: string;
        };
        CatalogUpdateRequest: {
            active: boolean;
            value: string;
        };
        ClientRequest: {
            /** Format: email */
            contactEmail?: string;
            documentNumber?: string;
            /** @enum {string} */
            documentType?: "RUC" | "DNI";
            name: string;
        };
        ClientResponse: {
            contactEmail?: string;
            documentNumber?: string;
            /** @enum {string} */
            documentType?: "RUC" | "DNI";
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        EquipmentRequest: {
            model: string;
            serialNumber?: string;
        };
        EquipmentResponse: {
            /** Format: int64 */
            clientId?: number;
            clientName?: string;
            /** Format: int64 */
            id?: number;
            model?: string;
            serialNumber?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: number;
            tokenType?: string;
        };
        TechnicalReportRequest: {
            /** Format: int64 */
            actionId: number;
            affectedComponent?: string;
            details: string;
            /** Format: date-time */
            endDatetime: string;
            /** Format: int64 */
            equipmentId: number;
            /** Format: int64 */
            eventFailureId: number;
            /** Format: int64 */
            finalStatusId: number;
            /** Format: int64 */
            initialStatusId: number;
            /** Format: int64 */
            personnelId: number;
            /** Format: date-time */
            startDatetime?: string;
            /** Format: int64 */
            supervisorId: number;
        };
        TechnicalReportResponse: {
            action?: components["schemas"]["CatalogResponse"];
            affectedComponent?: string;
            /** Format: int64 */
            clientId?: number;
            clientName?: string;
            /** Format: date-time */
            createdAt?: string;
            createdBy?: string;
            details?: string;
            /** Format: date-time */
            endDatetime?: string;
            /** Format: int64 */
            equipmentId?: number;
            equipmentModel?: string;
            equipmentSerialNumber?: string;
            eventFailure?: components["schemas"]["CatalogResponse"];
            finalStatus?: components["schemas"]["CatalogResponse"];
            /** Format: int64 */
            id?: number;
            initialStatus?: components["schemas"]["CatalogResponse"];
            personnel?: components["schemas"]["CatalogResponse"];
            reportNumber?: string;
            /** Format: date-time */
            startDatetime?: string;
            supervisor?: components["schemas"]["CatalogResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    findByType: {
        parameters: {
            query: {
                type: "ACTION" | "STATUS" | "EVENT_FAILURE" | "PERSONNEL" | "SUPERVISOR";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CatalogResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogCreateRequest"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    findAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
        };
    };
    findByClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EquipmentResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentRequest"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EquipmentResponse"];
                };
            };
        };
    };
    findById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EquipmentResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EquipmentResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll: {
        parameters: {
            query?: {
                clientId?: number;
                equipmentId?: number;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TechnicalReportResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicalReportRequest"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TechnicalReportResponse"];
                };
            };
        };
    };
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TechnicalReportResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicalReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TechnicalReportResponse"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
}
